<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist
  PUBLIC '-//Apple//DTD PLIST 1.0//EN'
  'http://www.apple.com/DTDs/PropertyList-1.0.dtd'>
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>nj</string>
      <string>njk</string>
      <string>nunjucks</string>
    </array>

    <key>name</key>
    <string>Nunjucks</string>

    <key>patterns</key>
    <array>

      <dict>
        <key>begin</key>
          <string>\[## comment ##\]</string>
        <key>end</key>
          <string>\[## endcomment ##\]</string>
        <key>name</key>
          <string>comment.block.nunjucks</string>
      </dict>

      <dict>
        <key>begin</key>
          <string>%!</string>
        <key>end</key>
          <string>!%</string>
        <key>name</key>
          <string>comment.line.nunjucks</string>
      </dict>

      <dict>
        <key>begin</key>
          <string>#!</string>
        <key>end</key>
          <string>!#</string>
        <key>name</key>
          <string>storage.type.var.nunjucks</string>
        <key>contentName</key>
          <string>variable.nunjucks</string>
        <key>patterns</key>
          <array>

            <dict>
            <key>include</key>
            <string>#inside_block</string>
            </dict>

          </array>
      </dict>

      <dict>
        <key>begin</key>
          <string>\[##</string>
        <key>end</key>
          <string>##\]</string>
        <key>name</key>
          <string>support.class.nunjucks</string>
        <key>contentName</key>
          <string>variable.nunjucks</string>
        <key>patterns</key>
          <array>

            <dict>
            <key>include</key>
            <string>#inside_block</string>
            </dict>

          </array>
      </dict>

    </array>

    <key>repository</key>
      <dict>

        <key>inside_block</key>
        <dict>
        <key>patterns</key>
        <array>

            <dict>
              <key>begin</key>
                <string>\w+\(</string>
              <key>end</key>
                <string>\)</string>
              <key>name</key>
                <string>entity.name.function.nunjucks</string>
              <key>contentName</key>
                <string>variable.nunjucks</string>
              <key>patterns</key>
                <array>

                  <dict>
                  <key>include</key>
                    <string>#inside_function</string>
                  </dict>

                </array>
            </dict>

            <dict>
              <key>begin</key>
                <string>"</string>
              <key>end</key>
                <string>"</string>
              <key>name</key>
                <string>string.nunjucks</string>
            </dict>

            <dict>
              <key>match</key>
                <string>((true|false|and|or|not)\b)</string>
              <key>name</key>
                <string>constant.language.nunjucks</string>
            </dict>

            <dict>
              <key>match</key>
                <string>((safe|title|capitalize|join|replace|escape|dump|first|float|groupby)\b)</string>
              <key>name</key>
                <string>storage.modifier.nunjucks</string>
            </dict>

            <dict>
              <key>match</key>
                <string>\|</string>
              <key>name</key>
                <string>keyword.operator.nunjucks</string>
            </dict>

            <dict>
              <key>match</key>
                <string>((macro|endmacro|from|import|if|for|endif|endfor|in|block|endblock|extends|else|new|include|set|as|with|context|filter|endfilter)\b)</string>
              <key>name</key>
                <string>variable.language.nunjucks</string>
            </dict>

        </array>
        </dict>

        <key>inside_function</key>
        <dict>
        <key>patterns</key>
        <array>
            <dict>
              <key>match</key>
                <string>(["'])(?:(?=(\\?))\2.)*?\1</string>
              <key>name</key>
                <string>string.nunjucks</string>
            </dict>

          </array>
          </dict>

      </dict>


    <key>scopeName</key>
    <string>text.html.nunjucks</string>
    <key>uuid</key>
    <string>0AAEDD0E-56AD-4B71-95C8-2FF271DE5B19</string>
  </dict>
</plist>
